### ISSUE TITLE
Consider adding 4-in-1 plot option for residual analysis plots

### ISSUE THREAD

**Issue by mattiasvillani** [StatisticsSU/regkurs#1]
Minitab has nice compact plot for residual analysis: https://support.minitab.com/en-us/minitab/18/help-and-how-to/modeling-statistics/regression/supporting-topics/residuals-and-residual-plots/residual-plots-in-minitab/

Would be nice if there was an option `4in1 = FALSE` in res.diagnostics.R that when set to true produced something similar.

**Comment by MaryAnne0725** [comment]
It is possible to do it with the following commands that I plan to add in the description of the file:

fit<-lm(sales~youtube+facebook,data=data)
png(file="plots.png")
par(mfrow=c(3,3), mar=c(5,5,2,2))
res.diagnostics(fit)
dev.off()

**Comment by MaryAnne0725** [comment]
In R-Studio you have the chans to see and export/save the file one by one and than with the commands that I wrote it is possible to have as a mosaic of plots.

**Comment by MaryAnne0725** [comment]
I have now the code with a flag: indicating all the plots together within the function, I plan at this point to introduce more flexibility: with three blocks: one for the residuals-outliers/expected value round 0, one block for the normality and one block for the regressors(in order to check the presence of patterns/constant variance).

**Comment by mattiasvillani** [comment]
That is very nice! But I would still add an optional argument that produces
the 4-in-1 plot using the code that you wrote here. There should be minimal
effort for the students to get a quick overview of the residuals. The
4-in-1 plots in Minitab is a good choice, or something like that. Just
my opinion.

**Comment by mattiasvillani** [comment]
Sorry, did not see you last reply. Sounds good. I will close this issue now.

**Comment by mattiasvillani** [comment]
Closing since MA is handling this now.
