### ISSUE TITLE
residual diagnostics - kernel density of residuals gets cut sometimes

### ISSUE THREAD

**Issue by mattiasvillani** [StatisticsSU/regkurs#2]
Set ylim in histogram for residuals so that both histogram and kernel density always shows in res.diagnostics(lmfit).

**Comment by MaryAnne0725** [comment]
I changed the code for it and now it is for values between 0 and 1. I added two commands in order to have clean area on the plot screen before to draw the actual plots

**Comment by mattiasvillani** [comment]
I modified the solution a bit. I am closing this issue now, since I think we have a handle on it now.
